In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

In [2]:
df = pd.read_csv('03-classification/course_lead_scoring_2026.csv')

In [3]:
df.isna().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [4]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [5]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
numerical = list(df.dtypes[df.dtypes != 'str'].index)

In [6]:
for c in categorical:
    df[c]=df[c].fillna('NA')
for j in numerical:
    df[j]=df[j].fillna(0.0)

In [7]:
df.isna().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

# Q1

In [8]:
df.industry.value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

# Q2

In [9]:
print(df[['interaction_count','number_of_courses_viewed']].corrwith(df.lead_score))
print(df[['number_of_courses_viewed','annual_income']].corrwith(df.interaction_count))

interaction_count           0.915746
number_of_courses_viewed    0.757204
dtype: float64
number_of_courses_viewed    0.721609
annual_income               0.122842
dtype: float64

In [10]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [11]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [12]:
y_train = df_train['converted'].values
y_val = df_val['converted'].values
y_test = df_test['converted'].values

In [13]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

# Q3

In [14]:
categorical_subset =['industry','location','lead_source','employment_status']

In [15]:
def mutual_info_churn_score(series):
    return np.round(mutual_info_score(series, df_full_train.converted),2)

In [16]:
mi = df_full_train[categorical_subset].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

lead_source          0.03
employment_status    0.02
location             0.00
industry             0.00
dtype: float64

# Q4

In [17]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
numerical = list(df.dtypes[df.dtypes != 'str'].index)
numerical.pop(-1)

'converted'

In [18]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [20]:
dv = DictVectorizer(sparse=False)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.fit_transform(val_dict)

y_pred = model.predict_proba(X_val)[:, 1]

In [21]:
churn_decision = (y_pred >= 0.5)

In [22]:
np.round((y_val == churn_decision).mean(),2)

np.float64(0.64)

# Q5

In [23]:
q4_accuracy = (y_val == churn_decision).mean()

In [24]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
numerical = list(df.dtypes[df.dtypes != 'str'].index)
numerical.pop(-1)
accuracy_list = []
lista_features=[]
columns= categorical + numerical

for c in columns:
    features_actuales = [col for col in columns if col != c]
    dv = DictVectorizer(sparse=False)
    
    train_dict = df_train[features_actuales].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    dv = DictVectorizer(sparse=False)
    val_dict = df_val[features_actuales].to_dict(orient='records')
    X_val = dv.fit_transform(val_dict)

    y_pred = model.predict_proba(X_val)[:, 1]
    churn_decision = (y_pred >= 0.5)
    accuracy=(y_val == churn_decision).mean()
    accuracy_list.append(accuracy)
    lista_features.append(c)

In [25]:
df_results = pd.DataFrame({
    'deleted_feature': lista_features,
    'accuracy': accuracy_list
})

In [26]:
df_results['accuracy_dif']= np.abs(q4_accuracy-df_results['accuracy'])

In [27]:
df_results[df_results['deleted_feature'].isin(['lead_source','number_of_courses_viewed','interaction_count'])].sort_values(by='accuracy_dif',ascending=True)

            deleted_feature  accuracy  accuracy_dif
5  number_of_courses_viewed     0.643         0.002
0               lead_source     0.642         0.003
6         interaction_count     0.601         0.044

# Q6

In [28]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
numerical = list(df.dtypes[df.dtypes != 'str'].index)
numerical.pop(-1)
columns= categorical + numerical
accuracy_list = []
lista_c= []

C=[0.000001, 0.00001, 0.0001, 0.001]
for c in C:
    dv = DictVectorizer(sparse=False)
    
    train_dict = df_train[columns].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    model = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    dv = DictVectorizer(sparse=False)
    val_dict = df_val[columns].to_dict(orient='records')
    X_val = dv.fit_transform(val_dict)

    y_pred = model.predict_proba(X_val)[:, 1]
    churn_decision = (y_pred >= 0.5)
    accuracy= np.round((y_val == churn_decision).mean(),3)
    accuracy_list.append(accuracy)
    lista_c.append(c)

In [29]:
df_results_2 = pd.DataFrame({
    'c_value': lista_c,
    'accuracy': accuracy_list
})

In [30]:
df_results_2.sort_values(by='accuracy',ascending=False)

    c_value  accuracy
3  0.001000     0.645
2  0.000100     0.613
1  0.000010     0.598
0  0.000001     0.598